### PR TITLE
Bug/map UI fixes

### LINKED ISSUE #128: Bug: fix search bar and navigation bar UIs and buttons
### Area

Mobile (Expo)

### Severity

Low (minor issue / cosmetic)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

When the search bar is displayed to input an address, it is white and looks like its styling is the default one. Once we click on the blue button to switch to "navigation mode" (where we can input a starting point and a destination), the navigation bar turns yellow. I would suggest sticking to consistent styling, so either making both white, or both yellow. I personally am not too much of a fan of the yellow as it clutters the UI and makes it look a bit messy. White would make it minimalistic and easier on the eyes. 

Also, the blue arrow isn't very intuitive to prompt the user to start navigation. Having tested these functions, I didn't instantly think of clicking on the blue arrow to start navigation. It actually looks like the "Locate Me" button, which could dissuade users from clicking on it to locate the building. This will most likely be pointed out during usability tests and should be addressed in future sprint.  

Also, The "stop" button in the navigation bar should not be the "circle with the bar" (the anti symbol) but instead be a small X in the corner of the navigation bar to close the navigation bar. This anti symbol actually looks like something that should not be clicked on, which dissuades users from click on it to close the nav bar. The bidirectional arrows that allow switching start and destination points should also be centered.

### Steps to Reproduce

1) Input a Concordia building (e.g., JMSB) in the search bar
2) Click on the blue arrow to start navigating
3) Navigation bar turns yellow

### Expected Behavior

- Consistent styling would be preferred to make it look less messy.
- Replace blue navigation button with a magnifying glass button.
- Replace the stop button with an X in the corner of the navigation bar.
- Center the bidirectional arrows.

### Actual Behavior

- Styling does not persist across actions (goes from white bar to yellow bar).
- Navigation button looks like a "locate me" button
- The stop navigation button looks like a button that should not be clicked on.
- The bidirectional arrows are not centered

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #158: Bug: Allow user to slide down the navigation bottom modal when in shuttle mode
### Area

Mobile (Expo)

### Severity

Medium (workaround exists)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

The navigation modal at the bottom of the page takes too much space when it's in shuttle mode. I would suggest making it minimizable so that the user can get a better view of the map, because it does get too cluttered.

### Steps to Reproduce

1) Input a departure point in the top navigation bar
2) Input a destination
3) Select Shuttle option

### Expected Behavior

The map should be well displayed and not too cluttered by the modals. The user should have an option of sliding it down to minimize it.

### Actual Behavior

The modal takes up at least a third of the screen, which clutters the UI and prevents the user from seeing the map and route well.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #170: Bug: Transit mode steps do not show bus numbers and metro lines
### Area

Mobile (Expo)

### Severity

Medium (workaround exists)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

Transit step instructions often show directional wording (for example, “take bus towards North”) but do not consistently show route identifiers such as bus numbers or metro line name/color. This can be confusing for real-life transit use.
API is definitely getting all the bus numbers, but just not displaying properly.

### Steps to Reproduce

1. Request a Transit route with bus or metro segments.
2. Start step-by-step navigation.
3. Review transit instructions in the panel.

### Expected Behavior

Transit line identifiers (e.g., bus number / metro lines with colours) are clearly visible in each relevant transit step, with directional text as secondary detail.

### Actual Behavior

Bus line directions are present, but any other metro context cues are not available. Harder for users to quickly confirm they are boarding the correct line.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #200: Bug: Review the "Start", "Directions", "Favourites" buttons in the building details modal
### Area

Mobile (Expo)

### Severity

Medium (workaround exists)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

When clicking on a building's details, there are 2 redundant buttons that do the same function (Start and Directions). Removing one would reduce clutter and eliminate redundancy.

All functional buttons (Directions, Indoor) should also be in the same colour tone as the "Directions" button so signal that the button is functional, or else users won't click on it.

Buttons to remove: Start, Favourites.

### Steps to Reproduce

1) Click on Hall building (or any building with indoor navigation)
2) View the details pop-up

### Expected Behavior

There should be only one button in the details modal that allows the user to start navigation. Typically, this would be the Directions button with the arrow icon. All functional buttons are also the same dark red to indicate that the button is functional.

### Actual Behavior

There shouldn't be 2 buttons replicating the same behaviour as this creates redundancy and can be confusing to the user. This also clutters the UI unnecessarily.

There is also a Favorites button next to it that does not lead to anything upon clicking (dead-click). If we don't plan on implementing something for it, we should remove it as well.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #206: Bug: Fix map elements (polygons, destination flag, mapbox tile)
### Area

Mobile (Expo)

### Severity

Low (minor issue / cosmetic)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

- Change the colours of the polygons to something more vibrant (less grey/vintage look) maybe by making the hive pattern darker red
- Change the flag that indicates the destination location (it should be a pin instead)
- Change the mapbox tile, if possible (the name of the buildings are greyed out and unclear)

### Steps to Reproduce

1) Click on any red building
2) Click on Directions
3) View flag that sets the building as the destination, try to read the building names.

### Expected Behavior

- The polygons should look more vibrant
- A pin should indicate the destination point.
- The building names should be clear to read.

### Actual Behavior

- Polygons look kind of outdated, faded.
- The flag icon that indicates the destination contributes to an unclean UI.
- The building names are not readable.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #208: Bug: Clicking anywhere on the bottom modal also selects map elements that lie under it
### Area

Mobile (Expo)

### Severity

Medium (workaround exists)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

The container of the bottom modal does not block whatever lies under it, so clicking it when a building happens to be under it will open that building's details.

### Steps to Reproduce

1) Slide map so that any Concordia building lies under the the bottom modal.
2) Click on the modal
3) The building's info pops up even though you don't mean to click on it.

### Expected Behavior

The bottom modal's container should "block" off whatever lies under it. The map portion that lies under the modal should not be clickable.

### Actual Behavior

The building's info pops up even though you don't mean to click on it when it happens to lie under the modal and you click on it.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

_No response_

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #209: Bug: SGW/LOY toggle does not update when switching between campuses
### Area

Mobile (Expo)

### Severity

Medium (workaround exists)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

When toggling between campuses (let's say toggle to Loyola), but your current location is set in SGW, clicking on the "locate me" button leads you back to SGW, but the toggle is still set to Loyola. In other words, the toggle does not update automatically when switching back and forth between campuses.

### Steps to Reproduce

1) Set current location to SGW
2) Set toggle button to Loyola 
2) Click on the "locate me" button

### Expected Behavior

Campus toggle should update automatically when you switch back and forth between campuses. Perhaps settings some bounds to set a campus radius can be the conditional that updates it.

### Actual Behavior

The toggle does not update automatically when switching back and forth between campuses.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image
Image

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### LINKED ISSUE #210: Bug: Shuttle modal UI edits
### Area

Mobile (Expo)

### Severity

Low (minor issue / cosmetic)

### Frequency

Always

### Platform

Android

### Device

Emulator

### Affected version (optional)

_No response_

### Endpoint / route (API only, optional)

_No response_

### Request details (API only, optional)

_No response_

### Summary

- The "Depart At"/"Arrive By" Button is not intuitive, it seems like a static button, which dissuades users from clicking on it to customize their departure/arrival time
- This button also does not become update as time passes. It becomes stale.
- The shuttle schedule is not intuitive. 

### Steps to Reproduce

1) Select any start and destination points
2) Start navigation
3) Select Shuttle as the mode of transportation

### Expected Behavior

- "Depart At"/"Arrive By" button should look editable, maybe putting a pencil icon next to it can increase call to action
- To have the time update in "Depart At"/"Arrive By", provide a refresh button so that it doesn't become stale.
- For the shuttle schedule, should have a toggle "--> SGW" and "--> LOY" that allows them to view schedules for both campuses no matter where they're leaving from. They should be able to toggle back and forth to view both shuttle directions

### Actual Behavior

- The "Depart At"/"Arrive By" Button seems like a static button, which dissuades users from clicking on it to customize their departure/arrival time
- This button also does not become update as time passes. It becomes stale.
- A specific direction of the shuttle schedule can only be viewed when departing from a specific campus. For example, if leaving from SGW, you can only see the schedule that goes towards LOY. The only way to see the schedule for the other direction is to use the bidirectional arrows in the navigation bar to switch start and destination points.

### Environment

_No response_

### Logs / Error Messages

_No response_

### Screenshots / Videos

Image

Image

Image

Notice how the time is 8:35PM and the Depart At button is still at 8:28PM.

### Regression?

_No response_

### Confirmation

- [x] I have searched for existing issues
- [x] I can reproduce this issue consistently

### PR DESCRIPTION
**Pull request by jenniferngu**
## Summary
- Closes #128 
- Closes #158 
- Closes #170 
- Closes #200 
- Closes #206 
- Closes #208 
- Closes #209 
- Closes #210 

## Why
UI changes had to be made to enhance user experience throughout HiveMaps. To understand why each change had to be made, see individual issues opened for each bug.

## Testing
- [x] Mobile unit: `cd hive-maps/apps/mobile && npm run test:ci`
- [x] API unit: `cd hive-maps/services/api && docker compose down -v && docker compose up -d --wait db && ./gradlew test`
- [x] API smoke: `cd hive-maps/services/api && docker compose up -d --build` then `curl http://localhost:8080/api/hello`
- [x] End-2-End Testing (script and screen-recording)
- [ ] If any item is not applicable, explain why:

## Checklist
- [x] I kept this PR focused.
- [x] I added/updated tests where needed, or this change does not require tests.
- [x] I updated docs where needed, or this change does not require docs updates.
- [x] I reviewed the acceptance criteria related to this user story and attached screenshots to the AT issue.
- [x] CI is green.
- [x] I have assigned the proper related items (reviewers, assignees, issues, branches, labels, etc)

### CODE REVIEW

File: hive-maps/apps/mobile/app/(tabs)/map.tsx [hunk 1]
```diff
@@ -707,8 +707,13 @@ export default function MapScreen() {
...
                     >
-                        <View style={{alignItems: 'center', justifyContent: 'center'}}>
-                            <Text style={{fontSize: 28, color: '#d32f2f'}}>🚩</Text>
+                        <View style={styles.destinationPinMarker}>
+                            <View style={styles.destinationPinBody}>
+                                <View style={styles.destinationPinInnerCircle}>
+                                    <View style={styles.destinationPinCenter} />
+                                </View>
+                            </View>
+                            <View style={styles.destinationPinStem} />
```
Comment (srabm) [inline hive-maps/apps/mobile/app/(tabs)/map.tsx]: 🔧 Would it be better to create a reusable pin component instead of nesting 4 View elements if it's reused in other places?
